### ISSUE TITLE
Coupling Graph doesn't work as expected

### ISSUE THREAD

**Issue by mcerejo** [Blazity/next-enterprise#283]
I was trying to create the graph.svg with the dependencies, but the command returns an error. Is it just me or does that implementation requires something more or its broken?

**Comment by wub** [comment]
What's the error?

**Comment by bmstefanski** [comment]
We can't do much without a screenshot of the error and your machine specs, os, cpu architecture, etc @mcerejo

**Comment by mcerejo** [comment]
![image](https://github.com/Blazity/next-enterprise/assets/110612277/2683fd98-0c5e-4af5-a645-d7ebeb5b9582)
![image](https://github.com/Blazity/next-enterprise/assets/110612277/7598ec81-a400-4e8e-8e80-2709addf43bb)

These are the errors that are triggered. The popup window is for the `tailwind.config.js`, `postcss.config.js`, `prettier.config.js`.

I'm using yarn (v1.22.19 and v4.1.1), node v18 on a windows 10 pc. 
![image](https://github.com/Blazity/next-enterprise/assets/110612277/e0cfe6c8-d928-49b9-b440-c9932a99ca3e)

**Comment by bmstefanski** [comment]
Thanks,

I am not sure what's the issue and can't test it on windows, but there are two things that you could try:
- (Must have) Install graphviz (not sure how to do that on Windows, but you you're using wsl, it should be possible), you can find the guide here https://github.com/pahen/madge#graphviz-optional and add it to the PATH manually https://github.com/pahen/madge#graphviz-optional
- Try executing that command directly in the console instead of running with yarn` "npx madge --extensions js,jsx,ts,tsx,css,md,mdx ./ --exclude '.next|tailwind.config.js|reset.d.ts|prettier.config.js|postcss.config.js|playwright.config.ts|next.config.js|next-env.d.ts|instrumentation.ts|e2e/|README.md|.storybook/|.eslintrc.js' --image graph.svg"`  - the fact that error says something about `next.config.js` tells me it could be an escaping issue
