### ISSUE TITLE
Stricter eslint

### ISSUE THREAD

**Issue by The-Code-Monkey** [Blazity/next-enterprise#294]
I feel like the eslint structure is too weak could be made much stricter for more consistent code, e.g. eslint-config-hardcore

**Comment by bmstefanski** [comment]
Hi @The-Code-Monkey , thanks for suggestion

What value would `eslint-config-hardcore` bring? I always prefer having a flexible convention instead of forcing anything, especially if it's eslint config - in my experience in real world codebases it ends up creating a lot of `// ts-ignore` comments even though every developer knows that they shouldn't use it 

It's possible for you to use that package though, just extend your config with that
